# Generated by Django 5.1.3 on 2024-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_song_song_yeardate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
