# Generated by Django 5.1.3 on 2024-11-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_song_song_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_writer',
            new_name='song_singer',
        ),
    ]
