# Generated by Django 5.1.3 on 2024-11-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_song_writer_song_song_singer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_yeardate',
            new_name='Annee',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_singer',
            new_name='Interprete',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_link',
            new_name='Lien',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_origin',
            new_name='Pays',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='Titre',
        ),
    ]
